# Generated by Django 3.0.8 on 2020-07-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passwd',
            new_name='PasswdModel',
        ),
    ]
