# Generated by Django 3.0.8 on 2020-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200722_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwdmodel',
            name='ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='passwdmodel',
            name='passwd',
            field=models.CharField(max_length=40),
        ),
    ]
